apiVersion: apps/v1
kind: Deployment
metadata:
  name: auto-deploy-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auto-deploy-demo
  template:
    metadata:
      labels:
        app: auto-deploy-demo
    spec:
      containers:
      - name: auto-deploy-demo
        image: 2200030228/auto-deploy-demo:1.0
        ports:
        - containerPort: 3000
